// AUTO-GENERATED by migrate.mjs — routing/metadata for each page.
// Each page body is a React component in src/pages/<slug>.jsx.
export const PAGES = {
  "3ds": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "3D Secure · Paysecure Docs"
  },
  "ach-payout": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "ACH Payout · Paysecure Docs"
  },
  "api-ach-payout": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: ACH Payout · Paysecure Docs"
  },
  "api-apms": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Bank &amp; local APMs · Paysecure Docs"
  },
  "api-applepay": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Apple Pay · Paysecure Docs"
  },
  "api-bank-transfers": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Bank Transfers · Paysecure Docs"
  },
  "api-cards": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Cards (S2S) · Paysecure Docs"
  },
  "api-cashier": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Cashier &amp; Session APIs · Paysecure Docs"
  },
  "api-crypto": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Crypto &amp; on-ramp · Paysecure Docs"
  },
  "api-cryptobridge": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: CryptoBridge · Paysecure Docs"
  },
  "api-fawrypay": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: FawryPay · Paysecure Docs"
  },
  "api-googlepay": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Google Pay · Paysecure Docs"
  },
  "api-interac-etransfer": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Interac e-Transfer · Paysecure Docs"
  },
  "api-interac-express": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Interac Express · Paysecure Docs"
  },
  "api-interac-request-money": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Interac Request Money · Paysecure Docs"
  },
  "api-mobilemoney": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: MobileMoney · Paysecure Docs"
  },
  "api-neosurf": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Neosurf · Paysecure Docs"
  },
  "api-onramp": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: OnRamp · Paysecure Docs"
  },
  "api-openbanking": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Open Banking · Paysecure Docs"
  },
  "api-partial-refunds": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Partial Refunds · Paysecure Docs"
  },
  "api-pay-with-crypto": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Pay with Crypto · Paysecure Docs"
  },
  "api-payid": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: PayID · Paysecure Docs"
  },
  "api-paymint": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Paymint · Paysecure Docs"
  },
  "api-payout-review": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Payout Manual Review · Paysecure Docs"
  },
  "api-paypal": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: PayPal Wallet · Paysecure Docs"
  },
  "api-pix": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: PIX · Paysecure Docs"
  },
  "api-preauth": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Pre-authorization · Paysecure Docs"
  },
  "api-recurring": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Recurring &amp; mandates · Paysecure Docs"
  },
  "api-reference": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Purchases · Paysecure Docs"
  },
  "api-skrill": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Skrill · Paysecure Docs"
  },
  "api-spei": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: SPEI · Paysecure Docs"
  },
  "api-thirdparty-upi": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: ThirdParty UPI · Paysecure Docs"
  },
  "api-tokenisation": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Network tokenisation · Paysecure Docs"
  },
  "api-save-a-card": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Save a Card · Paysecure Docs"
  },
  "api-transaction-reporting": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Transaction Reporting · Paysecure Docs"
  },
  "api-trust-score": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Trust Score · Paysecure Docs"
  },
  "api-upi": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: UPI Solution · Paysecure Docs"
  },
  "api-virtual-accounts": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Virtual Accounts (South Korea) · Paysecure Docs"
  },
  "api-virtual-cards-payout": {
    "navMode": "api",
    "noSide": false,
    "noToc": true,
    "innerClass": "content-inner wide",
    "innerStyle": "",
    "title": "API Reference: Virtual Cards Payout · Paysecure Docs"
  },
  "applepay": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Apple Pay · Paysecure Docs"
  },
  "bank-transfers": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Bank Transfers · Paysecure Docs"
  },
  "cards-2d": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "2D Payments · Paysecure Docs"
  },
  "cards": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Cards · Paysecure Docs"
  },
  "cryptobridge": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "CryptoBridge · Paysecure Docs"
  },
  "dash-add-user": {
    "navMode": "dashboard",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Add User · Paysecure Docs"
  },
  "dash-balance": {
    "navMode": "dashboard",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Balance · Paysecure Docs"
  },
  "dash-banks": {
    "navMode": "dashboard",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Banks · Paysecure Docs"
  },
  "dash-brand-settings": {
    "navMode": "dashboard",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Brand Settings · Paysecure Docs"
  },
  "dash-dashboard": {
    "navMode": "dashboard",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Dashboard · Paysecure Docs"
  },
  "dash-global-blocking": {
    "navMode": "dashboard",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Global Blocking · Paysecure Docs"
  },
  "dash-global-settings": {
    "navMode": "dashboard",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Global Settings · Paysecure Docs"
  },
  "dash-manage-roles": {
    "navMode": "dashboard",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Manage Roles · Paysecure Docs"
  },
  "dash-merchant-profile": {
    "navMode": "dashboard",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Merchant Profile · Paysecure Docs"
  },
  "dash-payouts": {
    "navMode": "dashboard",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Payouts · Paysecure Docs"
  },
  "dash-reports": {
    "navMode": "dashboard",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Reports and Analytics · Paysecure Docs"
  },
  "dash-rule-engine": {
    "navMode": "dashboard",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Rule Engine · Paysecure Docs"
  },
  "dash-utilities": {
    "navMode": "dashboard",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Utilities Module · Paysecure Docs"
  },
  "dashboard-configuration": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Dashboard configuration · Paysecure Docs"
  },
  "dashboard": {
    "navMode": "dashboard",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Merchant Onboarding and Configuration · Paysecure Docs"
  },
  "errors": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Statuses &amp; errors · Paysecure Docs"
  },
  "fawrypay": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "FawryPay · Paysecure Docs"
  },
  "getting-started": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Getting started · Paysecure Docs"
  },
  "googlepay": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Google Pay · Paysecure Docs"
  },
  "guides": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Guides · Paysecure Docs"
  },
  "index": {
    "navMode": "guides",
    "noSide": true,
    "noToc": true,
    "innerClass": "content-inner",
    "innerStyle": "max-width: 920px",
    "title": "Paysecure Developer Documentation"
  },
  "interac-etransfer": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Interac e-Transfer · Paysecure Docs"
  },
  "interac-express": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Interac Express · Paysecure Docs"
  },
  "interac-request-money": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Interac Request Money · Paysecure Docs"
  },
  "mobilemoney": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "MobileMoney · Paysecure Docs"
  },
  "neosurf": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Neosurf · Paysecure Docs"
  },
  "onramp": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "OnRamp · Paysecure Docs"
  },
  "openbanking": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Open Banking · Paysecure Docs"
  },
  "operations": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Operations: settlement, reconciliation, disputes · Paysecure Docs"
  },
  "pay-with-crypto": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Pay with Crypto · Paysecure Docs"
  },
  "payid": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "PayID · Paysecure Docs"
  },
  "payment-methods": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Payment methods · Paysecure Docs"
  },
  "paymint": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Paymint · Paysecure Docs"
  },
  "paypal": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "PayPal Wallet · Paysecure Docs"
  },
  "pix": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "PIX · Paysecure Docs"
  },
  "product-cashier": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Cashier · Paysecure Docs"
  },
  "product-payments": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Payments · Paysecure Docs"
  },
  "product-payouts": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Payouts · Paysecure Docs"
  },
  "product-preauth": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Pre-authorisation · Paysecure Docs"
  },
  "product-recurring": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Recurring payments · Paysecure Docs"
  },
  "product-reporting": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Reporting · Paysecure Docs"
  },
  "product-tokenisation": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Tokenisation · Paysecure Docs"
  },
  "quickstart": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Quickstart · Paysecure Docs"
  },
  "sandbox-credentials": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Sandbox &amp; API keys · Paysecure Docs"
  },
  "save-a-card": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Save a Card · Paysecure Docs"
  },
  "skrill": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Skrill · Paysecure Docs"
  },
  "spei": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "SPEI · Paysecure Docs"
  },
  "test-apm-simulator": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Test APM simulator · Paysecure Docs"
  },
  "test-cards": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Test cards · Paysecure Docs"
  },
  "thirdparty-upi": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "ThirdParty UPI · Paysecure Docs"
  },
  "udf": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "User-defined fields (UDF) · Paysecure Docs"
  },
  "upi": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "UPI Solution · Paysecure Docs"
  },
  "virtual-accounts": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Virtual Accounts (South Korea) · Paysecure Docs"
  },
  "virtual-cards-payout": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Virtual Cards Payout · Paysecure Docs"
  },
  "webhooks": {
    "navMode": "guides",
    "noSide": false,
    "noToc": false,
    "innerClass": "content-inner",
    "innerStyle": "",
    "title": "Webhooks · Paysecure Docs"
  }
};
